[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
id = "sql_database_credentials"
description = "Detects SQL connection strings with embedded credentials"
regex = '''(?i)(?:server|data\s+source|host)\s*=\s*[^;]{2,}[;\s]+.*?(?:password|pwd)\s*=\s*[^;"'\s]{3,}'''
path = '''(?i)\.(json|config|env|ini|yml|cs|xml|txt)$'''
tags = ["database","connection-string","credentials"]
